name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: |
            v1/${{ github.workflow }}/${{ runner.os }}/npm/${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v1/${{ github.workflow }}/${{ runner.os }}/npm/

      - run: npm ci
      - run: npm run build
